version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: itsyndicate-mysql
      working_dir: /application
      volumes:
        - ./application:/application
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=gklijhdsAG698547
        - MYSQL_DATABASE=itsyndicate
        - MYSQL_USER=someuser
        - MYSQL_PASSWORD=3lh4jr32qfelka
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: itsyndicate-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: itsyndicate-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    beanstalkd:
      image: schickling/beanstalkd
      container_name: itsyndicate-beanstalkd
      ports:
        - "11300:11300"

    composer:
      image: composer
      container_name: itsyndicate-composer
      volumes:
        - './application:/app'
      command: install